// Generated by gencpp from file ecobot/ussensor_mngt.msg
// DO NOT EDIT!


#ifndef ECOBOT_MESSAGE_USSENSOR_MNGT_H
#define ECOBOT_MESSAGE_USSENSOR_MNGT_H

#include <ros/service_traits.h>


#include <ecobot/ussensor_mngtRequest.h>
#include <ecobot/ussensor_mngtResponse.h>


namespace ecobot
{

struct ussensor_mngt
{

typedef ussensor_mngtRequest Request;
typedef ussensor_mngtResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ussensor_mngt
} // namespace ecobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ecobot::ussensor_mngt > {
  static const char* value()
  {
    return "4c3193c5a00d0932168fd4da30077568";
  }

  static const char* value(const ::ecobot::ussensor_mngt&) { return value(); }
};

template<>
struct DataType< ::ecobot::ussensor_mngt > {
  static const char* value()
  {
    return "ecobot/ussensor_mngt";
  }

  static const char* value(const ::ecobot::ussensor_mngt&) { return value(); }
};


// service_traits::MD5Sum< ::ecobot::ussensor_mngtRequest> should match
// service_traits::MD5Sum< ::ecobot::ussensor_mngt >
template<>
struct MD5Sum< ::ecobot::ussensor_mngtRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ecobot::ussensor_mngt >::value();
  }
  static const char* value(const ::ecobot::ussensor_mngtRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecobot::ussensor_mngtRequest> should match
// service_traits::DataType< ::ecobot::ussensor_mngt >
template<>
struct DataType< ::ecobot::ussensor_mngtRequest>
{
  static const char* value()
  {
    return DataType< ::ecobot::ussensor_mngt >::value();
  }
  static const char* value(const ::ecobot::ussensor_mngtRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ecobot::ussensor_mngtResponse> should match
// service_traits::MD5Sum< ::ecobot::ussensor_mngt >
template<>
struct MD5Sum< ::ecobot::ussensor_mngtResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ecobot::ussensor_mngt >::value();
  }
  static const char* value(const ::ecobot::ussensor_mngtResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ecobot::ussensor_mngtResponse> should match
// service_traits::DataType< ::ecobot::ussensor_mngt >
template<>
struct DataType< ::ecobot::ussensor_mngtResponse>
{
  static const char* value()
  {
    return DataType< ::ecobot::ussensor_mngt >::value();
  }
  static const char* value(const ::ecobot::ussensor_mngtResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ECOBOT_MESSAGE_USSENSOR_MNGT_H
